version: '4'

services:
  mongodb:
    image: mongo:7.0.5
    container_name: sc2_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: umut
      MONGO_INITDB_ROOT_PASSWORD: umut
      MONGO_INITDB_DATABASE: product
    volumes:
      - sc2_mongodb_vol:/data/db

  mysql:
    image: mysql:8.3.0
    container_name: sc2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: umut
      MYSQL_DATABASE: order
    ports:
      - "3306:3306"
    volumes:
      - sc2_mysql_vol:/var/lib/mysql

networks:
  sc2_network:
    driver: bridge

volumes:
  sc2_mysql_vol:
  sc2_mongodb_vol: