spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: umut
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081